version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: make build
      - store_artifacts:
          path: ./output/schema-go
          destination: schema-go
      - store_artifacts:
          path: ./output/schema-web
          destination: schema-web